filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
  fields:
    service: frontend
    type: nginx

- type: log
  enabled: true
  paths:
    - /var/log/app/*.log
  fields:
    service: backend
    type: application

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "frontend-logs-%{+yyyy.MM.dd}"
      when.equals:
        fields.service: "frontend"
    - index: "backend-logs-%{+yyyy.MM.dd}"
      when.equals:
        fields.service: "backend"

setup.kibana:
  host: "kibana:5601"

setup.template.enabled: true
setup.template.name: "trip-planner"
setup.template.pattern: "trip-planner-*"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
